// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Action {
    "task": string;
    "owner": string;
    "due": string;
    "done": boolean;

    /** Creates a new Action instance. */
    constructor($$source: Partial<Action> = {}) {
        if (!("task" in $$source)) {
            this["task"] = "";
        }
        if (!("owner" in $$source)) {
            this["owner"] = "";
        }
        if (!("due" in $$source)) {
            this["due"] = "";
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Action instance from a string or object.
     */
    static createFrom($$source: any = {}): Action {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Action($$parsedSource as Partial<Action>);
    }
}

/**
 * Analytics is a transcript-derived meeting summary.
 */
export class Analytics {
    /**
     * seconds anybody was talking
     */
    "speech": number;

    /**
     * seconds nobody was
     */
    "silence": number;

    /**
     * seconds two people were, at once
     */
    "overlap": number;

    /**
     * in the whole meeting
     */
    "words": number;

    /**
     * words per minute while somebody was talking
     */
    "pace": number;

    /**
     * most talkative first
     */
    "speakers": Voice[];

    /**
     * 0 = one person spoke, 1 = everyone equally
     */
    "balance": number;

    /**
     * the densest stretches, for the shape of the hour
     */
    "busiest": Moment[];

    /** Creates a new Analytics instance. */
    constructor($$source: Partial<Analytics> = {}) {
        if (!("speech" in $$source)) {
            this["speech"] = 0;
        }
        if (!("silence" in $$source)) {
            this["silence"] = 0;
        }
        if (!("overlap" in $$source)) {
            this["overlap"] = 0;
        }
        if (!("words" in $$source)) {
            this["words"] = 0;
        }
        if (!("pace" in $$source)) {
            this["pace"] = 0;
        }
        if (!("speakers" in $$source)) {
            this["speakers"] = [];
        }
        if (!("balance" in $$source)) {
            this["balance"] = 0;
        }
        if (!("busiest" in $$source)) {
            this["busiest"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Analytics instance from a string or object.
     */
    static createFrom($$source: any = {}): Analytics {
        const $$createField5_0 = $$createType1;
        const $$createField7_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("speakers" in $$parsedSource) {
            $$parsedSource["speakers"] = $$createField5_0($$parsedSource["speakers"]);
        }
        if ("busiest" in $$parsedSource) {
            $$parsedSource["busiest"] = $$createField7_0($$parsedSource["busiest"]);
        }
        return new Analytics($$parsedSource as Partial<Analytics>);
    }
}

/**
 * Briefing is the cross-meeting dashboard view.
 */
export class Briefing {
    "since": string;

    /**
     * in the window, newest first
     */
    "meetings": Recording[];

    /**
     * spent in them
     */
    "minutes": number;

    /**
     * what was settled, with where
     */
    "decided": Said[];

    /**
     * still open, oldest first
     */
    "mine": Outstanding[];

    /**
     * open, and their deadline has passed
     */
    "overdue": Outstanding[];

    /**
     * asked in more than one meeting and still open
     */
    "nagging": Nagging[];

    /**
     * who was in them
     */
    "voices": string[];

    /**
     * recordings the listener threw away
     */
    "skipped": number;

    /**
     * minutes it did not have to transcribe
     */
    "spared": number;

    /** Creates a new Briefing instance. */
    constructor($$source: Partial<Briefing> = {}) {
        if (!("since" in $$source)) {
            this["since"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("meetings" in $$source)) {
            this["meetings"] = [];
        }
        if (!("minutes" in $$source)) {
            this["minutes"] = 0;
        }
        if (!("decided" in $$source)) {
            this["decided"] = [];
        }
        if (!("mine" in $$source)) {
            this["mine"] = [];
        }
        if (!("overdue" in $$source)) {
            this["overdue"] = [];
        }
        if (!("nagging" in $$source)) {
            this["nagging"] = [];
        }
        if (!("voices" in $$source)) {
            this["voices"] = [];
        }
        if (!("skipped" in $$source)) {
            this["skipped"] = 0;
        }
        if (!("spared" in $$source)) {
            this["spared"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Briefing instance from a string or object.
     */
    static createFrom($$source: any = {}): Briefing {
        const $$createField1_0 = $$createType5;
        const $$createField3_0 = $$createType7;
        const $$createField4_0 = $$createType9;
        const $$createField5_0 = $$createType9;
        const $$createField6_0 = $$createType11;
        const $$createField7_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("meetings" in $$parsedSource) {
            $$parsedSource["meetings"] = $$createField1_0($$parsedSource["meetings"]);
        }
        if ("decided" in $$parsedSource) {
            $$parsedSource["decided"] = $$createField3_0($$parsedSource["decided"]);
        }
        if ("mine" in $$parsedSource) {
            $$parsedSource["mine"] = $$createField4_0($$parsedSource["mine"]);
        }
        if ("overdue" in $$parsedSource) {
            $$parsedSource["overdue"] = $$createField5_0($$parsedSource["overdue"]);
        }
        if ("nagging" in $$parsedSource) {
            $$parsedSource["nagging"] = $$createField6_0($$parsedSource["nagging"]);
        }
        if ("voices" in $$parsedSource) {
            $$parsedSource["voices"] = $$createField7_0($$parsedSource["voices"]);
        }
        return new Briefing($$parsedSource as Partial<Briefing>);
    }
}

export class Chapter {
    "start": number;
    "title": string;
    "summary": string;

    /** Creates a new Chapter instance. */
    constructor($$source: Partial<Chapter> = {}) {
        if (!("start" in $$source)) {
            this["start"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Chapter instance from a string or object.
     */
    static createFrom($$source: any = {}): Chapter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Chapter($$parsedSource as Partial<Chapter>);
    }
}

/**
 * Face is somebody heard in the project.
 */
export class Face {
    "name": string;
    "seconds": number;
    "meetings": number;
    "last": string;

    /** Creates a new Face instance. */
    constructor($$source: Partial<Face> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("seconds" in $$source)) {
            this["seconds"] = 0;
        }
        if (!("meetings" in $$source)) {
            this["meetings"] = 0;
        }
        if (!("last" in $$source)) {
            this["last"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Face instance from a string or object.
     */
    static createFrom($$source: any = {}): Face {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Face($$parsedSource as Partial<Face>);
    }
}

/**
 * Group is a user-managed folder for recordings.
 */
export class Group {
    "id": number;
    "name": string;
    "count": number;

    /**
     * empty means derived from the name
     */
    "colour": string;

    /** Creates a new Group instance. */
    constructor($$source: Partial<Group> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("colour" in $$source)) {
            this["colour"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Group instance from a string or object.
     */
    static createFrom($$source: any = {}): Group {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Group($$parsedSource as Partial<Group>);
    }
}

/**
 * Hit is one passage that matched a search.
 */
export class Hit {
    "recording": number;
    "title": string;
    "start": number;
    "speaker"?: string;
    "text": string;

    /** Creates a new Hit instance. */
    constructor($$source: Partial<Hit> = {}) {
        if (!("recording" in $$source)) {
            this["recording"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("start" in $$source)) {
            this["start"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Hit instance from a string or object.
     */
    static createFrom($$source: any = {}): Hit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Hit($$parsedSource as Partial<Hit>);
    }
}

/**
 * Kind is what a recording turned out to be.
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * somebody else was talking: diarized
     */
    Meeting = "meeting",

    /**
     * thinking aloud
     */
    Note = "note",
};

/**
 * KnowledgeHit preserves the source kind and owner.
 */
export class KnowledgeHit {
    "key": string;
    "kind": string;
    "recording": number;
    "project": number;
    "note": number;
    "title": string;
    "start": number;
    "text": string;

    /** Creates a new KnowledgeHit instance. */
    constructor($$source: Partial<KnowledgeHit> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("recording" in $$source)) {
            this["recording"] = 0;
        }
        if (!("project" in $$source)) {
            this["project"] = 0;
        }
        if (!("note" in $$source)) {
            this["note"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("start" in $$source)) {
            this["start"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KnowledgeHit instance from a string or object.
     */
    static createFrom($$source: any = {}): KnowledgeHit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KnowledgeHit($$parsedSource as Partial<KnowledgeHit>);
    }
}

/**
 * Mark is the lightweight recording shape the timeline draws.
 */
export class Mark {
    "id": number;
    "kind": Kind;
    "started": string;
    "duration": number;
    "folder": number;

    /** Creates a new Mark instance. */
    constructor($$source: Partial<Mark> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = Kind.$zero;
        }
        if (!("started" in $$source)) {
            this["started"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("folder" in $$source)) {
            this["folder"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Mark instance from a string or object.
     */
    static createFrom($$source: any = {}): Mark {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Mark($$parsedSource as Partial<Mark>);
    }
}

/**
 * Moment is one slice of the meeting timeline.
 */
export class Moment {
    "at": number;
    "words": number;

    /** Creates a new Moment instance. */
    constructor($$source: Partial<Moment> = {}) {
        if (!("at" in $$source)) {
            this["at"] = 0;
        }
        if (!("words" in $$source)) {
            this["words"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Moment instance from a string or object.
     */
    static createFrom($$source: any = {}): Moment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Moment($$parsedSource as Partial<Moment>);
    }
}

/**
 * Nagging is a question that keeps coming back.
 */
export class Nagging {
    "text": string;
    "times": number;
    "said": Said[];

    /** Creates a new Nagging instance. */
    constructor($$source: Partial<Nagging> = {}) {
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("times" in $$source)) {
            this["times"] = 0;
        }
        if (!("said" in $$source)) {
            this["said"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Nagging instance from a string or object.
     */
    static createFrom($$source: any = {}): Nagging {
        const $$createField2_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("said" in $$parsedSource) {
            $$parsedSource["said"] = $$createField2_0($$parsedSource["said"]);
        }
        return new Nagging($$parsedSource as Partial<Nagging>);
    }
}

/**
 * Outstanding is one action item from one meeting.
 */
export class Outstanding {
    "recording": number;
    "title": string;
    "started": string;
    "index": number;
    "task": string;
    "owner": string;
    "due": string;
    "done": boolean;

    /** Creates a new Outstanding instance. */
    constructor($$source: Partial<Outstanding> = {}) {
        if (!("recording" in $$source)) {
            this["recording"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("started" in $$source)) {
            this["started"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("task" in $$source)) {
            this["task"] = "";
        }
        if (!("owner" in $$source)) {
            this["owner"] = "";
        }
        if (!("due" in $$source)) {
            this["due"] = "";
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Outstanding instance from a string or object.
     */
    static createFrom($$source: any = {}): Outstanding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Outstanding($$parsedSource as Partial<Outstanding>);
    }
}

/**
 * Person is an enrolled speaker with saved voiceprints.
 */
export class Person {
    "id": number;
    "name": string;
    "samples": number;
    "meetings": number;

    /**
     * empty means derived from the name
     */
    "colour": string;
    "sources": Source[];

    /** Creates a new Person instance. */
    constructor($$source: Partial<Person> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("samples" in $$source)) {
            this["samples"] = 0;
        }
        if (!("meetings" in $$source)) {
            this["meetings"] = 0;
        }
        if (!("colour" in $$source)) {
            this["colour"] = "";
        }
        if (!("sources" in $$source)) {
            this["sources"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Person instance from a string or object.
     */
    static createFrom($$source: any = {}): Person {
        const $$createField5_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField5_0($$parsedSource["sources"]);
        }
        return new Person($$parsedSource as Partial<Person>);
    }
}

/**
 * Recording is one meeting or note.
 */
export class Recording {
    "id": number;
    "kind": Kind;

    /**
     * from the summary; the file name until then
     */
    "title": string;

    /**
     * file name under recordings/, empty once deleted
     */
    "audio": string;

    /**
     * which group it is filed under, 0 for none
     */
    "group": number;
    "started": string;
    "duration": number;
    "language": string;
    "status": Status;
    "progress": number;
    "problem"?: string;
    "summary"?: Summary | null;
    "speakers"?: string[];
    "turns": number;
    "note"?: string;

    /** Creates a new Recording instance. */
    constructor($$source: Partial<Recording> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = Kind.$zero;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("audio" in $$source)) {
            this["audio"] = "";
        }
        if (!("group" in $$source)) {
            this["group"] = 0;
        }
        if (!("started" in $$source)) {
            this["started"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = Status.$zero;
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("turns" in $$source)) {
            this["turns"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Recording instance from a string or object.
     */
    static createFrom($$source: any = {}): Recording {
        const $$createField11_0 = $$createType16;
        const $$createField12_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField11_0($$parsedSource["summary"]);
        }
        if ("speakers" in $$parsedSource) {
            $$parsedSource["speakers"] = $$createField12_0($$parsedSource["speakers"]);
        }
        return new Recording($$parsedSource as Partial<Recording>);
    }
}

/**
 * Rhythm is what the archive says about how the time goes: measured from the
 * recordings and their turns, with nothing scored or estimated.
 */
export class Rhythm {
    /**
     * oldest first, the current week last
     */
    "weeks": Week[];

    /**
     * Clock is minutes of meetings by weekday (Monday first) and hour of the
     * day, over the same weeks.
     */
    "clock": number[][];

    /**
     * Voices is who spoke over the last days asked for, most speech first.
     */
    "voices": Share[];

    /** Creates a new Rhythm instance. */
    constructor($$source: Partial<Rhythm> = {}) {
        if (!("weeks" in $$source)) {
            this["weeks"] = [];
        }
        if (!("clock" in $$source)) {
            this["clock"] = Array.from({ length: 7 }, () => Array.from({ length: 24 }, () => 0));
        }
        if (!("voices" in $$source)) {
            this["voices"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Rhythm instance from a string or object.
     */
    static createFrom($$source: any = {}): Rhythm {
        const $$createField0_0 = $$createType18;
        const $$createField2_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("weeks" in $$parsedSource) {
            $$parsedSource["weeks"] = $$createField0_0($$parsedSource["weeks"]);
        }
        if ("voices" in $$parsedSource) {
            $$parsedSource["voices"] = $$createField2_0($$parsedSource["voices"]);
        }
        return new Rhythm($$parsedSource as Partial<Rhythm>);
    }
}

/**
 * Said is one line from a summary, with its source meeting.
 */
export class Said {
    "recording": number;
    "title": string;
    "started": string;
    "text": string;

    /** Creates a new Said instance. */
    constructor($$source: Partial<Said> = {}) {
        if (!("recording" in $$source)) {
            this["recording"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("started" in $$source)) {
            this["started"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Said instance from a string or object.
     */
    static createFrom($$source: any = {}): Said {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Said($$parsedSource as Partial<Said>);
    }
}

/**
 * Share is how long one person spoke.
 */
export class Share {
    /**
     * empty for voices nobody has named
     */
    "speaker": string;
    "seconds": number;

    /** Creates a new Share instance. */
    constructor($$source: Partial<Share> = {}) {
        if (!("speaker" in $$source)) {
            this["speaker"] = "";
        }
        if (!("seconds" in $$source)) {
            this["seconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Share instance from a string or object.
     */
    static createFrom($$source: any = {}): Share {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Share($$parsedSource as Partial<Share>);
    }
}

/**
 * Source is where one voiceprint was taken from.
 */
export class Source {
    "recording": number;
    "speaker": string;
    "title": string;
    "audio": string;
    "start": number;
    "finish": number;

    /** Creates a new Source instance. */
    constructor($$source: Partial<Source> = {}) {
        if (!("recording" in $$source)) {
            this["recording"] = 0;
        }
        if (!("speaker" in $$source)) {
            this["speaker"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("audio" in $$source)) {
            this["audio"] = "";
        }
        if (!("start" in $$source)) {
            this["start"] = 0;
        }
        if (!("finish" in $$source)) {
            this["finish"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Source instance from a string or object.
     */
    static createFrom($$source: any = {}): Source {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Source($$parsedSource as Partial<Source>);
    }
}

/**
 * Standing is the mechanical project rollup built from stored meetings.
 */
export class Standing {
    "meetings": number;
    "hours": number;
    "first": string;
    "last": string;
    "work": Thread[];
    "decisions": Thread[];
    "questions": Thread[];
    "people": Face[];

    /**
     * Whether a model-authored project document is available.
     */
    "status": string;
    "written": boolean;

    /**
     * How many meetings the model-authored document has folded in so far.
     */
    "folded": number;

    /** Creates a new Standing instance. */
    constructor($$source: Partial<Standing> = {}) {
        if (!("meetings" in $$source)) {
            this["meetings"] = 0;
        }
        if (!("hours" in $$source)) {
            this["hours"] = 0;
        }
        if (!("first" in $$source)) {
            this["first"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("last" in $$source)) {
            this["last"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("work" in $$source)) {
            this["work"] = [];
        }
        if (!("decisions" in $$source)) {
            this["decisions"] = [];
        }
        if (!("questions" in $$source)) {
            this["questions"] = [];
        }
        if (!("people" in $$source)) {
            this["people"] = [];
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("written" in $$source)) {
            this["written"] = false;
        }
        if (!("folded" in $$source)) {
            this["folded"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Standing instance from a string or object.
     */
    static createFrom($$source: any = {}): Standing {
        const $$createField4_0 = $$createType22;
        const $$createField5_0 = $$createType22;
        const $$createField6_0 = $$createType22;
        const $$createField7_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("work" in $$parsedSource) {
            $$parsedSource["work"] = $$createField4_0($$parsedSource["work"]);
        }
        if ("decisions" in $$parsedSource) {
            $$parsedSource["decisions"] = $$createField5_0($$parsedSource["decisions"]);
        }
        if ("questions" in $$parsedSource) {
            $$parsedSource["questions"] = $$createField6_0($$parsedSource["questions"]);
        }
        if ("people" in $$parsedSource) {
            $$parsedSource["people"] = $$createField7_0($$parsedSource["people"]);
        }
        return new Standing($$parsedSource as Partial<Standing>);
    }
}

/**
 * Status is where a recording is in the pipeline.
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Queued = "queued",
    Transcribing = "transcribing",
    Summarising = "summarising",
    Done = "done",
    Failed = "failed",
};

/**
 * Sticky is a handwritten note owned by exactly one meeting or project.
 */
export class Sticky {
    "id": number;
    "recording": number;
    "project": number;
    "text": string;
    "colour": string;
    "at": number;

    /** Creates a new Sticky instance. */
    constructor($$source: Partial<Sticky> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("recording" in $$source)) {
            this["recording"] = 0;
        }
        if (!("project" in $$source)) {
            this["project"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("colour" in $$source)) {
            this["colour"] = "";
        }
        if (!("at" in $$source)) {
            this["at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Sticky instance from a string or object.
     */
    static createFrom($$source: any = {}): Sticky {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Sticky($$parsedSource as Partial<Sticky>);
    }
}

/**
 * Summary is the stored JSON summary payload.
 */
export class Summary {
    "title": string;
    "overview": string;
    "chapters": Chapter[];
    "topics": string[];
    "decisions": string[];
    "action_items": Action[];
    "open_questions": string[];

    /** Creates a new Summary instance. */
    constructor($$source: Partial<Summary> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("overview" in $$source)) {
            this["overview"] = "";
        }
        if (!("chapters" in $$source)) {
            this["chapters"] = [];
        }
        if (!("topics" in $$source)) {
            this["topics"] = [];
        }
        if (!("decisions" in $$source)) {
            this["decisions"] = [];
        }
        if (!("action_items" in $$source)) {
            this["action_items"] = [];
        }
        if (!("open_questions" in $$source)) {
            this["open_questions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     */
    static createFrom($$source: any = {}): Summary {
        const $$createField2_0 = $$createType26;
        const $$createField3_0 = $$createType12;
        const $$createField4_0 = $$createType12;
        const $$createField5_0 = $$createType28;
        const $$createField6_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("chapters" in $$parsedSource) {
            $$parsedSource["chapters"] = $$createField2_0($$parsedSource["chapters"]);
        }
        if ("topics" in $$parsedSource) {
            $$parsedSource["topics"] = $$createField3_0($$parsedSource["topics"]);
        }
        if ("decisions" in $$parsedSource) {
            $$parsedSource["decisions"] = $$createField4_0($$parsedSource["decisions"]);
        }
        if ("action_items" in $$parsedSource) {
            $$parsedSource["action_items"] = $$createField5_0($$parsedSource["action_items"]);
        }
        if ("open_questions" in $$parsedSource) {
            $$parsedSource["open_questions"] = $$createField6_0($$parsedSource["open_questions"]);
        }
        return new Summary($$parsedSource as Partial<Summary>);
    }
}

/**
 * Thread is one recurring line of work, one decision, or one open question.
 */
export class Thread {
    /**
     * The line's id in the kept document, or zero when this came from the fold.
     */
    "item": number;
    "state": string;
    "by": string;
    "pinned": boolean;
    "text": string;
    "owner": string;
    "due": string;
    "done": boolean;
    "times": number;

    /**
     * the meeting that said it last
     */
    "from": number;

    /**
     * its place in that meeting's action items
     */
    "index": number;
    "when": string;

    /** Creates a new Thread instance. */
    constructor($$source: Partial<Thread> = {}) {
        if (!("item" in $$source)) {
            this["item"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("by" in $$source)) {
            this["by"] = "";
        }
        if (!("pinned" in $$source)) {
            this["pinned"] = false;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("owner" in $$source)) {
            this["owner"] = "";
        }
        if (!("due" in $$source)) {
            this["due"] = "";
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }
        if (!("times" in $$source)) {
            this["times"] = 0;
        }
        if (!("from" in $$source)) {
            this["from"] = 0;
        }
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("when" in $$source)) {
            this["when"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Thread instance from a string or object.
     */
    static createFrom($$source: any = {}): Thread {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Thread($$parsedSource as Partial<Thread>);
    }
}

/**
 * Turn is one row of a transcript.
 */
export class Turn {
    "start": number;
    "end": number;
    "speaker"?: string;
    "text": string;

    /** Creates a new Turn instance. */
    constructor($$source: Partial<Turn> = {}) {
        if (!("start" in $$source)) {
            this["start"] = 0;
        }
        if (!("end" in $$source)) {
            this["end"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Turn instance from a string or object.
     */
    static createFrom($$source: any = {}): Turn {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Turn($$parsedSource as Partial<Turn>);
    }
}

/**
 * Voice is one person's share of a meeting.
 */
export class Voice {
    "speaker": string;
    "seconds": number;
    "share": number;
    "turns": number;

    /**
     * their longest single stretch
     */
    "longest": number;
    "words": number;

    /**
     * their own words per minute
     */
    "pace": number;

    /**
     * turns of theirs that asked something
     */
    "questions": number;

    /** Creates a new Voice instance. */
    constructor($$source: Partial<Voice> = {}) {
        if (!("speaker" in $$source)) {
            this["speaker"] = "";
        }
        if (!("seconds" in $$source)) {
            this["seconds"] = 0;
        }
        if (!("share" in $$source)) {
            this["share"] = 0;
        }
        if (!("turns" in $$source)) {
            this["turns"] = 0;
        }
        if (!("longest" in $$source)) {
            this["longest"] = 0;
        }
        if (!("words" in $$source)) {
            this["words"] = 0;
        }
        if (!("pace" in $$source)) {
            this["pace"] = 0;
        }
        if (!("questions" in $$source)) {
            this["questions"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Voice instance from a string or object.
     */
    static createFrom($$source: any = {}): Voice {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Voice($$parsedSource as Partial<Voice>);
    }
}

/**
 * Week is one Monday-to-Sunday stretch of meetings.
 */
export class Week {
    /**
     * its Monday, local midnight
     */
    "start": string;

    /**
     * recorded in meetings
     */
    "hours": number;
    "meetings": number;

    /**
     * written in those meetings' summaries
     */
    "decisions": number;

    /**
     * the same, for action items
     */
    "commitments": number;

    /** Creates a new Week instance. */
    constructor($$source: Partial<Week> = {}) {
        if (!("start" in $$source)) {
            this["start"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("hours" in $$source)) {
            this["hours"] = 0;
        }
        if (!("meetings" in $$source)) {
            this["meetings"] = 0;
        }
        if (!("decisions" in $$source)) {
            this["decisions"] = 0;
        }
        if (!("commitments" in $$source)) {
            this["commitments"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Week instance from a string or object.
     */
    static createFrom($$source: any = {}): Week {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Week($$parsedSource as Partial<Week>);
    }
}

// Private type creation functions
const $$createType0 = Voice.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Moment.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Recording.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = Said.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = Outstanding.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = Nagging.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $Create.Array($Create.Any);
const $$createType13 = Source.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = Summary.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = Week.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = Share.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = Thread.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = Face.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = Chapter.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = Action.createFrom;
const $$createType28 = $Create.Array($$createType27);
