// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Release is a published version of the app.
 */
export class Release {
    /**
     * 1.4.0
     */
    "version": string;
    "notes": string;
    "page": string;

    /** Creates a new Release instance. */
    constructor($$source: Partial<Release> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("page" in $$source)) {
            this["page"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Release instance from a string or object.
     */
    static createFrom($$source: any = {}): Release {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Release($$parsedSource as Partial<Release>);
    }
}
