// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as listen$0 from "../listen/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AcceptSummary(id: number, before: store$0.Summary | null, after: store$0.Summary | null): $CancellablePromise<void> {
    return $Call.ByID(3947130702, id, before, after);
}

/**
 * Actions lists outstanding action items across meetings.
 */
export function Actions(includeDone: boolean): $CancellablePromise<store$0.Outstanding[]> {
    return $Call.ByID(4286214473, includeDone).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Again retranscribes a recording from scratch.
 */
export function Again(id: number): $CancellablePromise<void> {
    return $Call.ByID(2388190674, id);
}

/**
 * Analytics returns transcript-derived meeting metrics.
 */
export function Analytics(id: number): $CancellablePromise<store$0.Analytics | null> {
    return $Call.ByID(2094126650, id).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Appearances lists the groups a person appears in, busiest first.
 */
export function Appearances(name: string): $CancellablePromise<store$0.Group[]> {
    return $Call.ByID(1939080865, name).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Ask answers a question from the transcripts.
 */
export function Ask(question: string): $CancellablePromise<$models.Answer | null> {
    return $Call.ByID(1500112095, question).then(($result: any) => {
        return $$createType7($result);
    });
}

export function AskKnowledge(question: string): $CancellablePromise<$models.KnowledgeAnswer | null> {
    return $Call.ByID(1254955373, question).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * Bin lists recordings currently in the bin.
 */
export function Bin(): $CancellablePromise<store$0.Recording[]> {
    return $Call.ByID(820010799).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * Brief returns the cross-meeting briefing view.
 */
export function Brief(days: number): $CancellablePromise<store$0.Briefing | null> {
    return $Call.ByID(690406538, days).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * Delete buries a meeting.
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(2789016269, id);
}

/**
 * DropGroup removes a group and leaves its recordings unfiled.
 */
export function DropGroup(id: number): $CancellablePromise<void> {
    return $Call.ByID(974174766, id);
}

export function EditAction(id: number, index: number, action: store$0.Action): $CancellablePromise<void> {
    return $Call.ByID(1423411092, id, index, action);
}

/**
 * EmptyBin permanently deletes everything currently in the bin.
 */
export function EmptyBin(): $CancellablePromise<string> {
    return $Call.ByID(1597412084);
}

/**
 * File assigns a recording to a group, or clears the assignment when group is
 * zero.
 */
export function File(recording: number, group: number): $CancellablePromise<void> {
    return $Call.ByID(4262653172, recording, group);
}

/**
 * Forget drops a learned person.
 */
export function Forget(name: string): $CancellablePromise<void> {
    return $Call.ByID(3211396467, name);
}

/**
 * Groups lists library groups.
 */
export function Groups(): $CancellablePromise<store$0.Group[]> {
    return $Call.ByID(3017561026).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Import copies a file into the recordings folder and queues it.
 */
export function Import(path: string): $CancellablePromise<store$0.Recording | null> {
    return $Call.ByID(2393183823, path).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * InGroup lists one group's recordings.
 */
export function InGroup(group: number): $CancellablePromise<store$0.Recording[]> {
    return $Call.ByID(2924641732, group).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * Listener installs the always-on recorder once it is ready.
 */
export function Listener(r: listen$0.Recorder | null): $CancellablePromise<void> {
    return $Call.ByID(1729818974, r);
}

/**
 * Listening reports the recorder state for polling UI.
 */
export function Listening(): $CancellablePromise<listen$0.Status> {
    return $Call.ByID(2744938035).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * Live returns the current live transcript.
 */
export function Live(): $CancellablePromise<listen$0.Line[]> {
    return $Call.ByID(2531093944).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * Loose reports how many recordings belong to no group.
 */
export function Loose(): $CancellablePromise<number> {
    return $Call.ByID(3074855652);
}

/**
 * MCPStatus reports whether external AI clients can reach the app.
 */
export function MCPStatus(): $CancellablePromise<$models.MCPState> {
    return $Call.ByID(4054666384).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * Markdown renders a whole meeting for export.
 */
export function Markdown(id: number): $CancellablePromise<string> {
    return $Call.ByID(1704503591, id);
}

/**
 * Moment returns where a line occurred within a recording.
 */
export function Moment(recording: number, text: string): $CancellablePromise<number> {
    return $Call.ByID(1538936198, recording, text);
}

/**
 * NewGroup creates a group or returns the existing one with that name.
 */
export function NewGroup(name: string): $CancellablePromise<store$0.Group> {
    return $Call.ByID(2951344047, name).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Notes(recording: number, project: number): $CancellablePromise<store$0.Sticky[]> {
    return $Call.ByID(3870704023, recording, project).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * Open loads one recording and its transcript.
 */
export function Open(id: number): $CancellablePromise<$models.Meeting | null> {
    return $Call.ByID(3169510906, id).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * Paint sets or clears a group's explicit colour.
 */
export function Paint(id: number, colour: string): $CancellablePromise<void> {
    return $Call.ByID(2169964894, id, colour);
}

/**
 * PaintPerson sets or clears a person's explicit colour.
 */
export function PaintPerson(name: string, colour: string): $CancellablePromise<void> {
    return $Call.ByID(1523618083, name, colour);
}

/**
 * People lists everybody the app can recognise by voice.
 */
export function People(): $CancellablePromise<store$0.Person[]> {
    return $Call.ByID(3465037041).then(($result: any) => {
        return $$createType24($result);
    });
}

/**
 * PinItem is a person editing a line of the project document; from then on the
 * model may close it but never reword it.
 */
export function PinItem(group: number, id: number, text: string, owner: string, due: string): $CancellablePromise<void> {
    return $Call.ByID(1162602530, group, id, text, owner, due);
}

/**
 * Playing tells the listener when app-owned playback is running.
 */
export function Playing(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(1269014556, on);
}

export function PreviewSummary(id: number): $CancellablePromise<store$0.Summary | null> {
    return $Call.ByID(1815224778, id).then(($result: any) => {
        return $$createType26($result);
    });
}

export function PutNote(note: store$0.Sticky): $CancellablePromise<store$0.Sticky> {
    return $Call.ByID(4192976983, note).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * RebuildProject replays every meeting into a fresh document. The answer to
 * "this has gone wrong".
 */
export function RebuildProject(group: number): $CancellablePromise<void> {
    return $Call.ByID(3236221742, group);
}

/**
 * Recent lists recordings newest first.
 */
export function Recent(limit: number): $CancellablePromise<store$0.Recording[]> {
    return $Call.ByID(1420283577, limit).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * Record toggles manual recording.
 */
export function Record(): $CancellablePromise<void> {
    return $Call.ByID(2466039479);
}

/**
 * Redate corrects when a meeting really happened.
 */
export function Redate(recording: number, when: string): $CancellablePromise<void> {
    return $Call.ByID(2426394395, recording, when);
}

/**
 * Reindex fills in any missing passage embeddings.
 */
export function Reindex(): $CancellablePromise<string> {
    return $Call.ByID(2651234501);
}

export function RemoveNote(id: number): $CancellablePromise<void> {
    return $Call.ByID(2502196882, id);
}

/**
 * Rename changes a speaker's label throughout one meeting and teaches the
 * matching voice when possible.
 */
export function Rename(id: number, $from: string, to: string): $CancellablePromise<void> {
    return $Call.ByID(3355732220, id, $from, to);
}

/**
 * RenameGroup renames a group.
 */
export function RenameGroup(id: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(3567885487, id, name);
}

/**
 * Restore takes a recording back out of the bin.
 */
export function Restore(id: number): $CancellablePromise<void> {
    return $Call.ByID(2469582744, id);
}

/**
 * Retitle overrides the model-generated title.
 */
export function Retitle(id: number, title: string): $CancellablePromise<void> {
    return $Call.ByID(1977650231, id, title);
}

/**
 * RevealFolder opens the app folder in the platform file manager.
 */
export function RevealFolder(): $CancellablePromise<void> {
    return $Call.ByID(4141902131);
}

/**
 * Samples lists the evidence behind a learned person.
 */
export function Samples(name: string): $CancellablePromise<store$0.Source[]> {
    return $Call.ByID(1556926209, name).then(($result: any) => {
        return $$createType28($result);
    });
}

/**
 * SaveNote stores a note against a meeting.
 */
export function SaveNote(id: number, note: string): $CancellablePromise<void> {
    return $Call.ByID(2773378063, id, note);
}

/**
 * SaveSettings writes settings back to disk.
 */
export function SaveSettings(s: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(1260496690, s);
}

/**
 * Search finds passages across every transcript.
 */
export function Search(query: string): $CancellablePromise<store$0.Hit[]> {
    return $Call.ByID(1634764442, query).then(($result: any) => {
        return $$createType30($result);
    });
}

export function SearchKnowledge(query: string, semantic: boolean): $CancellablePromise<store$0.KnowledgeHit[]> {
    return $Call.ByID(3922664222, query, semantic).then(($result: any) => {
        return $$createType32($result);
    });
}

export function Settings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(4203116247).then(($result: any) => {
        return $$createType33($result);
    });
}

/**
 * Span returns recent recordings for the timeline.
 */
export function Span(days: number): $CancellablePromise<store$0.Mark[]> {
    return $Call.ByID(3717387314, days).then(($result: any) => {
        return $$createType35($result);
    });
}

/**
 * Standing returns one group's current standing.
 */
export function Standing(group: number): $CancellablePromise<store$0.Standing | null> {
    return $Call.ByID(1016657098, group).then(($result: any) => {
        return $$createType37($result);
    });
}

/**
 * Summaries reports whether LLM-backed features are configured.
 */
export function Summaries(): $CancellablePromise<boolean> {
    return $Call.ByID(2534345830);
}

/**
 * Summarise reruns summary generation for a recording.
 */
export function Summarise(id: number): $CancellablePromise<void> {
    return $Call.ByID(2369526854, id);
}

/**
 * ThisIsMe names the laptop owner and backfills any usable self voiceprints.
 */
export function ThisIsMe(name: string): $CancellablePromise<string> {
    return $Call.ByID(821810460, name);
}

/**
 * Tick marks one action item done or undone.
 */
export function Tick(id: number, index: number, done: boolean): $CancellablePromise<void> {
    return $Call.ByID(2083712087, id, index, done);
}

/**
 * TickItem ticks a line of the project document off, or puts it back.
 */
export function TickItem(group: number, id: number, done: boolean): $CancellablePromise<void> {
    return $Call.ByID(929529136, group, id, done);
}

/**
 * Tidy runs the audio-retention sweep now.
 */
export function Tidy(): $CancellablePromise<string> {
    return $Call.ByID(2386150514);
}

/**
 * Waveform returns the loudness envelope of the folded playback audio.
 */
export function Waveform(id: number): $CancellablePromise<number[]> {
    return $Call.ByID(1962206177, id).then(($result: any) => {
        return $$createType38($result);
    });
}

// Private type creation functions
const $$createType0 = store$0.Outstanding.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = store$0.Analytics.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = store$0.Group.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.Answer.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.KnowledgeAnswer.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = store$0.Recording.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = store$0.Briefing.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $Create.Nullable($$createType10);
const $$createType15 = listen$0.Status.createFrom;
const $$createType16 = listen$0.Line.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = $models.MCPState.createFrom;
const $$createType19 = store$0.Sticky.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $models.Meeting.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = store$0.Person.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = store$0.Summary.createFrom;
const $$createType26 = $Create.Nullable($$createType25);
const $$createType27 = store$0.Source.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = store$0.Hit.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = store$0.KnowledgeHit.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = $models.Settings.createFrom;
const $$createType34 = store$0.Mark.createFrom;
const $$createType35 = $Create.Array($$createType34);
const $$createType36 = store$0.Standing.createFrom;
const $$createType37 = $Create.Nullable($$createType36);
const $$createType38 = $Create.Array($Create.Any);
