// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as listen$0 from "../listen/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AIStatus is polled by the settings screen.
 */
export function AIStatus(): $CancellablePromise<$models.AIState> {
    return $Call.ByID(1321556140).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AcceptSummary(id: number, before: store$0.Summary | null, after: store$0.Summary | null): $CancellablePromise<void> {
    return $Call.ByID(3376420516, id, before, after);
}

/**
 * Actions lists outstanding action items across meetings.
 */
export function Actions(includeDone: boolean): $CancellablePromise<store$0.Outstanding[]> {
    return $Call.ByID(930980495, includeDone).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Again retranscribes a recording from scratch.
 */
export function Again(id: number): $CancellablePromise<void> {
    return $Call.ByID(3133342296, id);
}

/**
 * Analytics returns transcript-derived meeting metrics.
 */
export function Analytics(id: number): $CancellablePromise<store$0.Analytics | null> {
    return $Call.ByID(1461344700, id).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * Appearances lists the groups a person appears in, busiest first.
 */
export function Appearances(name: string): $CancellablePromise<store$0.Group[]> {
    return $Call.ByID(3509876839, name).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ApplyAI builds the model client the settings describe and puts it to work.
 * Whatever it still needs is fetched in the background, after which it is
 * applied again.
 */
export function ApplyAI(): $CancellablePromise<void> {
    return $Call.ByID(2336324454);
}

/**
 * Ask answers a question from the transcripts.
 */
export function Ask(question: string): $CancellablePromise<$models.Answer | null> {
    return $Call.ByID(3095791229, question).then(($result: any) => {
        return $$createType8($result);
    });
}

export function AskKnowledge(question: string): $CancellablePromise<$models.KnowledgeAnswer | null> {
    return $Call.ByID(3873997683, question).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * Bin lists recordings currently in the bin.
 */
export function Bin(): $CancellablePromise<store$0.Recording[]> {
    return $Call.ByID(571756861).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * Brief returns the cross-meeting briefing view.
 */
export function Brief(days: number): $CancellablePromise<store$0.Briefing | null> {
    return $Call.ByID(4262578916, days).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * CheckUpdate asks for a newer release now, for the button in the settings.
 */
export function CheckUpdate(): $CancellablePromise<void> {
    return $Call.ByID(190121965);
}

/**
 * ConnectCopilot signs in to GitHub Copilot in the browser. It returns at once;
 * AIStatus follows the sign-in.
 */
export function ConnectCopilot(): $CancellablePromise<void> {
    return $Call.ByID(1734679706);
}

/**
 * Copilot reports the signed-in GitHub account and its models. It starts the
 * Copilot CLI for a moment, so the settings screen asks once when it opens.
 */
export function Copilot(): $CancellablePromise<$models.CopilotAccount> {
    return $Call.ByID(2332418300).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * Delete buries a meeting.
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(2031587407, id);
}

/**
 * DropGroup removes a group and leaves its recordings unfiled.
 */
export function DropGroup(id: number): $CancellablePromise<void> {
    return $Call.ByID(2122627240, id);
}

export function EditAction(id: number, index: number, action: store$0.Action): $CancellablePromise<void> {
    return $Call.ByID(2433312858, id, index, action);
}

/**
 * EmptyBin permanently deletes everything currently in the bin.
 */
export function EmptyBin(): $CancellablePromise<string> {
    return $Call.ByID(1358074942);
}

/**
 * File assigns a recording to a group, or clears the assignment when group is
 * zero.
 */
export function File(recording: number, group: number): $CancellablePromise<void> {
    return $Call.ByID(1529290802, recording, group);
}

/**
 * Forget drops a learned person.
 */
export function Forget(name: string): $CancellablePromise<void> {
    return $Call.ByID(802904725, name);
}

/**
 * Groups lists library groups.
 */
export function Groups(): $CancellablePromise<store$0.Group[]> {
    return $Call.ByID(69688140).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * Hold pauses the recording in progress without ending it, or resumes it.
 */
export function Hold(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(1425432153, on);
}

/**
 * Import copies a file into the recordings folder and queues it.
 */
export function Import(path: string): $CancellablePromise<store$0.Recording | null> {
    return $Call.ByID(323991049, path).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * InGroup lists one group's recordings.
 */
export function InGroup(group: number): $CancellablePromise<store$0.Recording[]> {
    return $Call.ByID(4247314098, group).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * InstallUpdate downloads and prepares the newer release behind the window;
 * Update follows it, and RestartToUpdate finishes it.
 */
export function InstallUpdate(): $CancellablePromise<void> {
    return $Call.ByID(2723163598);
}

/**
 * Listener installs the always-on recorder once it is ready.
 */
export function Listener(r: listen$0.Recorder | null): $CancellablePromise<void> {
    return $Call.ByID(1016634708, r);
}

/**
 * Listening reports the recorder state for polling UI.
 */
export function Listening(): $CancellablePromise<listen$0.Status> {
    return $Call.ByID(3260884793).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * Live returns the current live transcript.
 */
export function Live(): $CancellablePromise<listen$0.Line[]> {
    return $Call.ByID(857624286).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * Loose reports how many recordings belong to no group.
 */
export function Loose(): $CancellablePromise<number> {
    return $Call.ByID(296371398);
}

/**
 * MCPStatus reports whether external AI clients can reach the app.
 */
export function MCPStatus(): $CancellablePromise<$models.MCPState> {
    return $Call.ByID(2364504538).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * Markdown renders a whole meeting for export.
 */
export function Markdown(id: number): $CancellablePromise<string> {
    return $Call.ByID(3816970797, id);
}

/**
 * Moment returns where a line occurred within a recording.
 */
export function Moment(recording: number, text: string): $CancellablePromise<number> {
    return $Call.ByID(2116253744, recording, text);
}

/**
 * MoveStrip remembers where the strip was left.
 */
export function MoveStrip(x: number, y: number): $CancellablePromise<void> {
    return $Call.ByID(4144228317, x, y);
}

/**
 * NewGroup creates a group or returns the existing one with that name.
 */
export function NewGroup(name: string): $CancellablePromise<store$0.Group> {
    return $Call.ByID(4199650165, name).then(($result: any) => {
        return $$createType5($result);
    });
}

export function Notes(recording: number, project: number): $CancellablePromise<store$0.Sticky[]> {
    return $Call.ByID(4102202713, recording, project).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * Open loads one recording and its transcript.
 */
export function Open(id: number): $CancellablePromise<$models.Meeting | null> {
    return $Call.ByID(252157860, id).then(($result: any) => {
        return $$createType24($result);
    });
}

/**
 * Paint sets or clears a group's explicit colour.
 */
export function Paint(id: number, colour: string): $CancellablePromise<void> {
    return $Call.ByID(3404773384, id, colour);
}

/**
 * PaintPerson sets or clears a person's explicit colour.
 */
export function PaintPerson(name: string, colour: string): $CancellablePromise<void> {
    return $Call.ByID(1043564333, name, colour);
}

/**
 * PauseFor stops the app recording anything for that many minutes, for a
 * private conversation in the room; 0 ends the pause. A recording in progress
 * is filed first.
 */
export function PauseFor(minutes: number): $CancellablePromise<void> {
    return $Call.ByID(1461332421, minutes);
}

/**
 * People lists everybody the app can recognise by voice.
 */
export function People(): $CancellablePromise<store$0.Person[]> {
    return $Call.ByID(2015584423).then(($result: any) => {
        return $$createType26($result);
    });
}

/**
 * PinItem is a person editing a line of the project document; from then on the
 * model may close it but never reword it.
 */
export function PinItem(group: number, id: number, text: string, owner: string, due: string): $CancellablePromise<void> {
    return $Call.ByID(3864148116, group, id, text, owner, due);
}

/**
 * Playing tells the listener when app-owned playback is running.
 */
export function Playing(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(1598357826, on);
}

export function PreviewSummary(id: number): $CancellablePromise<store$0.Summary | null> {
    return $Call.ByID(3893433528, id).then(($result: any) => {
        return $$createType28($result);
    });
}

export function PutNote(note: store$0.Sticky): $CancellablePromise<store$0.Sticky> {
    return $Call.ByID(2127520261, note).then(($result: any) => {
        return $$createType21($result);
    });
}

/**
 * RebuildProject replays every meeting into a fresh document. The answer to
 * "this has gone wrong".
 */
export function RebuildProject(group: number): $CancellablePromise<void> {
    return $Call.ByID(1955865216, group);
}

/**
 * Recent lists recordings newest first.
 */
export function Recent(limit: number): $CancellablePromise<store$0.Recording[]> {
    return $Call.ByID(2151622735, limit).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * Record toggles manual recording.
 */
export function Record(): $CancellablePromise<void> {
    return $Call.ByID(297470353);
}

/**
 * Redate corrects when a meeting really happened.
 */
export function Redate(recording: number, when: string): $CancellablePromise<void> {
    return $Call.ByID(131040217, recording, when);
}

/**
 * Reindex fills in any missing search vectors.
 */
export function Reindex(): $CancellablePromise<$models.Indexed> {
    return $Call.ByID(1676040235).then(($result: any) => {
        return $$createType29($result);
    });
}

export function RemoveNote(id: number): $CancellablePromise<void> {
    return $Call.ByID(4288311552, id);
}

/**
 * Rename changes a speaker's label throughout one meeting and teaches the
 * matching voice when possible.
 */
export function Rename(id: number, $from: string, to: string): $CancellablePromise<void> {
    return $Call.ByID(3231081830, id, $from, to);
}

/**
 * RenameGroup renames a group.
 */
export function RenameGroup(id: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(1043173145, id, name);
}

/**
 * RestartToUpdate quits the app and opens the new version in its place. It
 * refuses while a recording is in progress.
 */
export function RestartToUpdate(): $CancellablePromise<void> {
    return $Call.ByID(1636821395);
}

/**
 * Restore takes a recording back out of the bin.
 */
export function Restore(id: number): $CancellablePromise<void> {
    return $Call.ByID(583232174, id);
}

/**
 * Retitle overrides the model-generated title.
 */
export function Retitle(id: number, title: string): $CancellablePromise<void> {
    return $Call.ByID(4081148809, id, title);
}

/**
 * RevealFolder opens the app folder in the platform file manager.
 */
export function RevealFolder(): $CancellablePromise<void> {
    return $Call.ByID(951261417);
}

/**
 * Rhythm measures how the meetings of the last twelve weeks were spread, and
 * who spoke over the last days.
 */
export function Rhythm(days: number): $CancellablePromise<store$0.Rhythm | null> {
    return $Call.ByID(1909494132, days).then(($result: any) => {
        return $$createType31($result);
    });
}

/**
 * Rush transcribes one queued recording next, whatever the schedule says.
 */
export function Rush(id: number): $CancellablePromise<void> {
    return $Call.ByID(600156654, id);
}

/**
 * Samples lists the evidence behind a learned person.
 */
export function Samples(name: string): $CancellablePromise<store$0.Source[]> {
    return $Call.ByID(3779078695, name).then(($result: any) => {
        return $$createType33($result);
    });
}

/**
 * SaveNote stores a note against a meeting.
 */
export function SaveNote(id: number, note: string): $CancellablePromise<void> {
    return $Call.ByID(3867637305, id, note);
}

/**
 * SaveSettings writes settings back to disk. AI changes apply at once.
 */
export function SaveSettings(s: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(4293299692, s);
}

/**
 * Search finds passages across every transcript.
 */
export function Search(query: string): $CancellablePromise<store$0.Hit[]> {
    return $Call.ByID(3261299832, query).then(($result: any) => {
        return $$createType35($result);
    });
}

export function SearchKnowledge(query: string, semantic: boolean): $CancellablePromise<store$0.KnowledgeHit[]> {
    return $Call.ByID(4128673916, query, semantic).then(($result: any) => {
        return $$createType37($result);
    });
}

export function Settings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(912023337).then(($result: any) => {
        return $$createType38($result);
    });
}

/**
 * Span returns recent recordings for the timeline.
 */
export function Span(days: number): $CancellablePromise<store$0.Mark[]> {
    return $Call.ByID(613994076, days).then(($result: any) => {
        return $$createType40($result);
    });
}

/**
 * Standing returns one group's current standing.
 */
export function Standing(group: number): $CancellablePromise<store$0.Standing | null> {
    return $Call.ByID(1867745684, group).then(($result: any) => {
        return $$createType42($result);
    });
}

/**
 * StripAt is where the recording strip was last left, in points from the
 * primary display's top-left; false when it was never moved.
 */
export function StripAt(): $CancellablePromise<[number, number, boolean]> {
    return $Call.ByID(2203587151);
}

/**
 * Summaries reports whether summaries and answers can be made right now.
 */
export function Summaries(): $CancellablePromise<boolean> {
    return $Call.ByID(2160594968);
}

/**
 * Summarise reruns summary generation for a recording.
 */
export function Summarise(id: number): $CancellablePromise<void> {
    return $Call.ByID(2461017992, id);
}

/**
 * ThisIsMe names the laptop owner and backfills any usable self voiceprints. It
 * returns how many recordings the voice was learnt from.
 */
export function ThisIsMe(name: string): $CancellablePromise<number> {
    return $Call.ByID(50897806, name);
}

/**
 * Tick marks one action item done or undone.
 */
export function Tick(id: number, index: number, done: boolean): $CancellablePromise<void> {
    return $Call.ByID(2363834169, id, index, done);
}

/**
 * TickItem ticks a line of the project document off, or puts it back.
 */
export function TickItem(group: number, id: number, done: boolean): $CancellablePromise<void> {
    return $Call.ByID(3333829746, group, id, done);
}

/**
 * Tidy runs the audio-retention sweep now.
 */
export function Tidy(): $CancellablePromise<$models.Tidied> {
    return $Call.ByID(2734074620).then(($result: any) => {
        return $$createType43($result);
    });
}

/**
 * Update is polled by the interface.
 */
export function Update(): $CancellablePromise<$models.UpdateState> {
    return $Call.ByID(774779877).then(($result: any) => {
        return $$createType44($result);
    });
}

/**
 * Usage reports what the models were asked and what it cost over the last days.
 */
export function Usage(days: number): $CancellablePromise<$models.UsageReport> {
    return $Call.ByID(1054112523, days).then(($result: any) => {
        return $$createType45($result);
    });
}

/**
 * WatchUpdates asks for a newer release now and then every hour, until ctx ends.
 * Switched off in the settings, it asks nothing.
 */
export function WatchUpdates(): $CancellablePromise<void> {
    return $Call.ByID(4033382319);
}

/**
 * Waveform returns the loudness envelope of the folded playback audio.
 */
export function Waveform(id: number): $CancellablePromise<number[]> {
    return $Call.ByID(1827314399, id).then(($result: any) => {
        return $$createType46($result);
    });
}

// Private type creation functions
const $$createType0 = $models.AIState.createFrom;
const $$createType1 = store$0.Outstanding.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = store$0.Analytics.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = store$0.Group.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.Answer.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $models.KnowledgeAnswer.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = store$0.Recording.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = store$0.Briefing.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = $models.CopilotAccount.createFrom;
const $$createType16 = $Create.Nullable($$createType11);
const $$createType17 = listen$0.Status.createFrom;
const $$createType18 = listen$0.Line.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = $models.MCPState.createFrom;
const $$createType21 = store$0.Sticky.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = $models.Meeting.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = store$0.Person.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = store$0.Summary.createFrom;
const $$createType28 = $Create.Nullable($$createType27);
const $$createType29 = $models.Indexed.createFrom;
const $$createType30 = store$0.Rhythm.createFrom;
const $$createType31 = $Create.Nullable($$createType30);
const $$createType32 = store$0.Source.createFrom;
const $$createType33 = $Create.Array($$createType32);
const $$createType34 = store$0.Hit.createFrom;
const $$createType35 = $Create.Array($$createType34);
const $$createType36 = store$0.KnowledgeHit.createFrom;
const $$createType37 = $Create.Array($$createType36);
const $$createType38 = $models.Settings.createFrom;
const $$createType39 = store$0.Mark.createFrom;
const $$createType40 = $Create.Array($$createType39);
const $$createType41 = store$0.Standing.createFrom;
const $$createType42 = $Create.Nullable($$createType41);
const $$createType43 = $models.Tidied.createFrom;
const $$createType44 = $models.UpdateState.createFrom;
const $$createType45 = $models.UsageReport.createFrom;
const $$createType46 = $Create.Array($Create.Any);
