// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

/**
 * Answer is an LLM reply plus the passages it cites.
 */
export class Answer {
    "text": string;
    "sources": store$0.Hit[];

    /** Creates a new Answer instance. */
    constructor($$source: Partial<Answer> = {}) {
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("sources" in $$source)) {
            this["sources"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Answer instance from a string or object.
     */
    static createFrom($$source: any = {}): Answer {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField1_0($$parsedSource["sources"]);
        }
        return new Answer($$parsedSource as Partial<Answer>);
    }
}

export class KnowledgeAnswer {
    "text": string;
    "sources": store$0.KnowledgeHit[];

    /** Creates a new KnowledgeAnswer instance. */
    constructor($$source: Partial<KnowledgeAnswer> = {}) {
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("sources" in $$source)) {
            this["sources"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KnowledgeAnswer instance from a string or object.
     */
    static createFrom($$source: any = {}): KnowledgeAnswer {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField1_0($$parsedSource["sources"]);
        }
        return new KnowledgeAnswer($$parsedSource as Partial<KnowledgeAnswer>);
    }
}

/**
 * MCPState is the local server status shown in Settings.
 */
export class MCPState {
    "status": string;
    "url": string;
    "command": string;
    "problem"?: string;

    /** Creates a new MCPState instance. */
    constructor($$source: Partial<MCPState> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPState instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MCPState($$parsedSource as Partial<MCPState>);
    }
}

/**
 * Meeting is one recording with its transcript.
 */
export class Meeting {
    "id": number;
    "kind": store$0.Kind;

    /**
     * from the summary; the file name until then
     */
    "title": string;

    /**
     * file name under recordings/, empty once deleted
     */
    "audio": string;

    /**
     * which group it is filed under, 0 for none
     */
    "group": number;
    "started": string;
    "duration": number;
    "language": string;
    "status": store$0.Status;
    "progress": number;
    "problem"?: string;
    "summary"?: store$0.Summary | null;
    "speakers"?: string[];
    "turns": number;
    "note"?: string;
    "transcript": store$0.Turn[];

    /** Creates a new Meeting instance. */
    constructor($$source: Partial<Meeting> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = store$0.Kind.$zero;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("audio" in $$source)) {
            this["audio"] = "";
        }
        if (!("group" in $$source)) {
            this["group"] = 0;
        }
        if (!("started" in $$source)) {
            this["started"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = store$0.Status.$zero;
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("turns" in $$source)) {
            this["turns"] = 0;
        }
        if (!("transcript" in $$source)) {
            this["transcript"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Meeting instance from a string or object.
     */
    static createFrom($$source: any = {}): Meeting {
        const $$createField11_0 = $$createType5;
        const $$createField12_0 = $$createType6;
        const $$createField15_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField11_0($$parsedSource["summary"]);
        }
        if ("speakers" in $$parsedSource) {
            $$parsedSource["speakers"] = $$createField12_0($$parsedSource["speakers"]);
        }
        if ("transcript" in $$parsedSource) {
            $$parsedSource["transcript"] = $$createField15_0($$parsedSource["transcript"]);
        }
        return new Meeting($$parsedSource as Partial<Meeting>);
    }
}

/**
 * Settings is the payload the settings screen reads and writes.
 */
export class Settings {
    "language": string;
    "openaiKey": string;
    "openaiModel": string;
    "summarise": string;
    "keepNotes": boolean;
    "density": string;
    "listening": boolean;

    /**
     * System captures machine audio alongside the microphone.
     */
    "system": boolean;

    /**
     * seconds of talking before it records
     */
    "startSpeech": number;

    /**
     * seconds of silence that end it
     */
    "quietEnds": number;

    /**
     * seconds it reaches back when it starts
     */
    "preroll": number;

    /**
     * 0 keeps recordings for ever
     */
    "keepAudioDays": number;
    "folder": string;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("openaiKey" in $$source)) {
            this["openaiKey"] = "";
        }
        if (!("openaiModel" in $$source)) {
            this["openaiModel"] = "";
        }
        if (!("summarise" in $$source)) {
            this["summarise"] = "";
        }
        if (!("keepNotes" in $$source)) {
            this["keepNotes"] = false;
        }
        if (!("density" in $$source)) {
            this["density"] = "";
        }
        if (!("listening" in $$source)) {
            this["listening"] = false;
        }
        if (!("system" in $$source)) {
            this["system"] = false;
        }
        if (!("startSpeech" in $$source)) {
            this["startSpeech"] = 0;
        }
        if (!("quietEnds" in $$source)) {
            this["quietEnds"] = 0;
        }
        if (!("preroll" in $$source)) {
            this["preroll"] = 0;
        }
        if (!("keepAudioDays" in $$source)) {
            this["keepAudioDays"] = 0;
        }
        if (!("folder" in $$source)) {
            this["folder"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

/**
 * Stage is the first-run setup stage.
 */
export enum Stage {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * fetching models on first run
     */
    Downloading = "downloading",

    /**
     * opening them, which takes seconds
     */
    Loading = "loading",
    Ready = "ready",
    Broken = "broken",
};

/**
 * State is the first-run status snapshot.
 */
export class State {
    "stage": Stage;

    /**
     * which model, in words
     */
    "what": string;

    /**
     * 0..1 across the whole download
     */
    "fraction": number;
    "done": number;
    "total": number;
    "problem"?: string;

    /** Creates a new State instance. */
    constructor($$source: Partial<State> = {}) {
        if (!("stage" in $$source)) {
            this["stage"] = Stage.$zero;
        }
        if (!("what" in $$source)) {
            this["what"] = "";
        }
        if (!("fraction" in $$source)) {
            this["fraction"] = 0;
        }
        if (!("done" in $$source)) {
            this["done"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     */
    static createFrom($$source: any = {}): State {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new State($$parsedSource as Partial<State>);
    }
}

// Private type creation functions
const $$createType0 = store$0.Hit.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = store$0.KnowledgeHit.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = store$0.Summary.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = store$0.Turn.createFrom;
const $$createType8 = $Create.Array($$createType7);
